services:
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - COSMOS_URI=https://heart-disease-prediction-db.documents.azure.com:443/
      - COSMOS_SECRET=${COSMOS_SECRET}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_SSL=false
      - FLASK_ENV=test
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api