services:
  api:
    image: heartdiseaseprediction.azurecr.io/api:latest
    container_name: api
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - COSMOS_URI=https://heart-disease-prediction-db.documents.azure.com:443/
      - COSMOS_SECRET=${COSMOS_SECRET}
      - REDIS_HOST=heart-disease-prediction-cache.redis.cache.windows.net
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  frontend:
    image: heartdiseaseprediction.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - api